name: ST-ItemEditor
main: net.starly.itemeditor.ItemEditorMain
author: Starly Team
website: http://starly.kr/discord

api-version: 1.13
version: 1.2.2

softdepend:
  - ST-Core

commands:
  itemeditor:
    description: 아이템 편집기 명령어입니다.
    aliases: [ ie, 아이템, 아이템편집 ]