name: ST-ItemEditor
main: net.starly.itemeditor.ItemEditorMain
author: Starly Team
website: http://starly.kr/discord

api-version: 1.14
version: 1.1.3

softdepend:
  - ST-Core

commands:
  itemeditor:
    description: 아이템 에디터 명령어입니다.
    aliases: [ ie, 아이템, 아이템편집 ]